blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Wenutu/TaskPanel/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/Wenutu/TaskPanel/blob/main/README.md
    about: Read the full documentation and examples
