name: Build Package

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.6'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: List built packages
      run: |
        echo "Built packages:"
        ls -la dist/

    - name: Upload taskpanel package
      uses: actions/upload-artifact@v4
      with:
        name: taskpanel-package
        path: dist/
        retention-days: 7
