name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        # Python 3.6 and 3.7 are End-of-Life (EOL) and not pre-installed on runners.
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    # KEY STEP: For EOL Python versions, add the deadsnakes PPA and install them manually.
    - name: Add deadsnakes PPA and install old Python versions
      if: matrix.python-version == '3.6' || matrix.python-version == '3.7'
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        # Install the specific python version, its distutils, and venv modules.
        sudo apt-get install -y python${{ matrix.python-version }} python${{ matrix.python-version }}-distutils python${{ matrix.python-version }}-venv

    - name: Set up Python ${{ matrix.python-version }}
      # setup-python is smart enough to find the version we just installed.
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install pytest pytest-cov
        pip install flake8 black

    - name: Lint with flake8
      run: |
        # Use a relaxed flake8 configuration.
        flake8 src/taskpanel tests/ --config=.flake8

    - name: Check code formatting with black
      run: |
        # Fail the job if formatting is incorrect.
        black --check --diff --line-length=88 src/taskpanel/ tests/

    - name: Install package
      run: |
        pip install -e .

    - name: Run tests
      run: |
        python -m pytest tests/ -v --cov=src/taskpanel --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.python-version == '3.11' # Only upload coverage once to save time.
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # Recommended for private repos
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  build:
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    # KEY STEP: Install Python 3.6 using the deadsnakes PPA.
    - name: Add deadsnakes PPA and install Python 3.6
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.6 python3.6-distutils python3.6-venv

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.6'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check package
      run: twine check dist/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  security:
    needs: test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    # KEY STEP: Install Python 3.6 using the deadsnakes PPA.
    - name: Add deadsnakes PPA and install Python 3.6
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install -y python3.6 python3.6-distutils python3.6-venv

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.6'

    - name: Install dependencies for security check
      run: |
        python -m pip install --upgrade pip
        # Install the package itself to check its dependencies.
        pip install -e .
        pip install safety

    - name: Run safety checks
      run: |
        # Check the installed environment for vulnerabilities. Fails the job if any are found.
        safety check